Enable reactivating/deleting a project
opheeelia/standup pull request #25
Opened 2022-12-04 22:22 UTC by amy-lei

Attempting to delete will open a warning first since the action is more permanent
<img width="358" alt="image" src="https://user-images.githubusercontent.com/42757189/205518817-5dc2c60d-887d-4f70-b78b-95e4128b7673.png">
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/42757189/205518859-c5620d97-ec75-43ba-994b-aa5078820b4d.png">

2022-12-07 14:38 UTC, opheeelia commented
Maybe also hide the create an update button when a project is marked as completed?

2022-12-07 15:35 UTC, opheeelia requested changes
Maybe also hide the create an update button when a project is marked as completed?

2022-12-07 22:05 UTC, amy-lei commented
> Maybe also hide the create an update button when a project is marked as completed?

Good idea! Done.

2022-12-08 05:43 UTC, opheeelia approved these changes

2022-12-08 22:53 UTC, merged